all:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I ../../Dependencies/vincent/include -I ../../Library/Include ../../Dependencies/vincent/source/test.cpp ../../Dependencies/vincent/source/test_result.cpp ../../Tests/runner.cpp ../../Library/Source/Simulation/Database.cpp ../../Library/Source/Events/EventManager.cpp ../../Library/Source/Exception.cpp -o tmp/test
	./tmp/test
