all:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I ../../Dependencies/vincent/include ../../Dependencies/vincent/source/test.cpp ../../Dependencies/vincent/source/test_result.cpp ../../Tests/runner.cpp -o tmp/test
	./tmp/test
